# ==============================================================================
# TITOLO:       LDAP Tuning 2/3: Ottimizzazione dell'Overlay SyncProv
# AUTORE:       Elia Pinto
# DATA:         Luglio 2026
# VERSIONE:     1.7 (Local LDAPS/LDAPI - FIXED INDEXED DN)
# SCOPO:        Inizializzare e ottimizzare l'overlay SyncProv per la replica
#               N-Way Multi-Master garantendo la tenuta dei buffer in RAM.
# ==============================================================================

---
- name: "LDAP Tuning 2/3: Ottimizzazione dell'Overlay SyncProv"
  hosts: cluster
  become: true
  vars:
    stato: "enable"

  tasks:
    - name: "[ENABLE] Carica il modulo globale syncprov"
      community.general.ldap_attrs:
        server_uri: "ldapi:///"
        sasl_class: "external"
        dn: "cn=module{0},cn=config"
        attributes:
          olcModuleLoad: "syncprov"
        state: present
      when: stato == "enable"

    - name: "[ENABLE] Inizializza l'overlay syncprov sul database mdb"
      community.general.ldap_entry:
        server_uri: "ldapi:///"
        sasl_class: "external"
        dn: "olcOverlay={0}syncprov,olcDatabase={1}mdb,cn=config"
        objectClass:
          - olcSyncProvConfig
          - olcOverlayConfig
        attributes:
          olcOverlay: "syncprov"
        state: present
      when: stato == "enable"

    - name: "[TUNING] Forza l'applicazione dei parametri sul Database MDB via LDIF"
      ansible.builtin.shell: |
        ldapmodify -Y EXTERNAL -H ldapi:/// <<EOF
        dn: olcOverlay={0}syncprov,olcDatabase={1}mdb,cn=config
        changetype: modify
        replace: olcSpSessionlog
        olcSpSessionlog: 5000
        -
        replace: olcSpCheckpoint
        olcSpCheckpoint: 10000 10
        EOF
      register: ldif_tuning_result
      changed_when: "'modifying entry' in ldif_tuning_result.stdout"
      failed_when: ldif_tuning_result.rc != 0
      when: stato == "enable"
