# ==============================================================================
# TITOLO:       Ottimizzazione, Tuning Performance e Nesting OpenLDAP (cn=config)
# AUTORE:       Elia Pinto
# DATA:         Luglio 2026
# VERSIONE:     1.7 (TLS Hardened)
# SCOPO:        Ottimizzare OpenLDAP (Back-MDB) per infrastrutture Cloud.
#               Configura indici, pool di thread e inizializza l'overlay 
#               memberOf abilitando il nesting ricorsivo reale dei gruppi.
# ==============================================================================

---
- name: Ottimizzazione e Configurazione OpenLDAP (cn=config)
  hosts: cluster
  become: true
  vars:
    stato: "enabled"
    ldap_auth:
      server_uri: "ldapi:///"
      sasl_class: "external"

  tasks:
    - name: "[SETUP] Installa la libreria python3-ldap nativa di sistema"
      ansible.builtin.apt:
        name: python3-ldap
        state: present
        update_cache: yes

    - name: "[ENABLE] Configura i parametri globali di slapd (Threads e Pending)"
      community.general.ldap_attrs:
        server_uri: "{{ ldap_auth.server_uri }}"
        sasl_class: "{{ ldap_auth.sasl_class }}"
        dn: "cn=config"
        attributes:
          olcThreads: 16
          olcConnMaxPending: 100
          olcConnMaxPendingAuth: 50
        state: exact
      when: stato in ['enable', 'enabled']

#    - name: "[ENABLE] Carica il modulo globale memberof"
##     community.general.ldap_attrs:
#        server_uri: "{{ ldap_auth.server_uri }}"
#        sasl_class: "{{ ldap_auth.sasl_class }}"
#        dn: "cn=module{0},cn=config"
#        attributes:
#          olcModuleLoad: "memberof.la"
#        state: present
#      when: stato in ['enable', 'enabled']

#    - name: "[ENABLE] Inizializza l'entry dell'overlay memberOf con supporto NESTING"
#      community.general.ldap_entry:
#      server_uri: "{{ ldap_auth.server_uri }}"
#      sasl_class: "{{ ldap_auth.sasl_class }}"
#      dn: "olcOverlay={0}memberof,olcDatabase={1}mdb,cn=config"
#      objectClass:
#       - olcMemberOf
#       - olcOverlayConfig
#      attributes:
#       olcOverlay: "memberof"
#       olcMemberOfRefInt: "TRUE"
#       olcMemberOfGroupOC: "groupOfNames"
#       olcMemberOfMemberAD: "member"
#       olcMemberOfMemberOfAD: "memberOf"
#       state: present
#       when: stato in ['enable', 'enabled']

    - name: "[ENABLE] Ottimizza MaxSize e Indici sul database mdb"
      community.general.ldap_attrs:
        server_uri: "{{ ldap_auth.server_uri }}"
        sasl_class: "{{ ldap_auth.sasl_class }}"
        dn: "olcDatabase={1}mdb,cn=config"
        attributes:
          olcDbMaxSize: "4294967296"
          olcDbIndex:
            - "objectClass eq"
            - "uid eq"
            - "cn eq,sub"
            - "member eq"
            - "memberUid eq"
            - "memberOf eq"
        state: exact
      when: stato in ['enable', 'enabled']
